#!/bin/bash

DOTPATH=~/dotfiles; export DOTPATH
GITHUB_URL="https://github.com/shinshu68/dotfiles.git"; export GITHUB_URL
MIRROR_URL="http://ftp.jaist.ac.jp/pub/Linux/ubuntu/"

is_exists() {
    which "$1" >/dev/null 2>&1
    return $?
}

e_done() {
    printf " \033[37;1m%s\033[m...\033[32mOK\033[m\n" "✔ $*"
}

print_dotfiles_header() {
    printf "\e[34m"
    echo '---------------------------------------------------------------------------------------'
    echo '                                                                                       '
    echo '                 888            888      .d888  d8b  888                               '
    echo '                 888            888     d88P"   Y8P  888                               '
    echo '                 888            888     888          888                               '
    echo '             .d88888   .d88b.   888888  888888  888  888   .d88b.   .d8888b            '
    echo '            d88" 888  d88""88b  888     888     888  888  d8P  Y8b  88K                '
    echo '            888  888  888  888  888     888     888  888  88888888  "Y8888b.           '
    echo '            Y88b 888  Y88..88P  Y88b.   888     888  888  Y8b.           X88           '
    echo '             "Y88888   "Y88P"    "Y888  888     888  888   "Y8888    88888P"           '
    echo '                                                                                       '
    echo '---------------------------------------------------------------------------------------'
    printf "\e[0m\n"
}

set_apt_mirror() {
    local sources='/etc/apt/sources.list.d/ubuntu.sources'

    # Ubuntu 24.04 以降は deb822 形式の ubuntu.sources に設定がある
    if [ -f "$sources" ]; then
        if grep -q "$MIRROR_URL" "$sources"; then
            echo 'Already set apt mirror'
            return
        fi

        echo 'Setting apt mirror...'
        # security.ubuntu.com はミラーせず、archive.ubuntu.com だけを書き換える
        sudo sed -i".back" -E "s|^URIs: http://([a-z]+\.)?archive\.ubuntu\.com/ubuntu/?$|URIs: $MIRROR_URL|" "$sources"
    else
        echo 'Setting apt mirror...'
        sudo sed -i".back" -e 's/\/\/archive.ubuntu.com/\/\/ftp.jaist.ac.jp\/pub\/Linux/g' /etc/apt/sources.list
    fi

    e_done "Set apt mirror"
}

install_ansible() {
    if is_exists "ansible"; then
        echo 'Already installed ansible'
        return
    fi

    echo 'Installing ansible...'

    # software-properties-common と gnupg は playbook で PPA を追加するときに使う
    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ansible git curl gnupg software-properties-common

    e_done "Install ansible"
}

download_dotfiles() {
    if [ -d "$DOTPATH" ]; then
        echo 'Already downloaded dotfiles'
        return
    fi

    echo 'Downloading dotfiles...'

    if is_exists "git"; then
        git clone "$GITHUB_URL" "$DOTPATH"

    elif is_exists "curl"; then
        local tar_url="https://github.com/shinshu68/dotfiles/archive/master.tar.gz"
        curl -sL "$tar_url" | tar xvz >/dev/null 2>&1

        if [ ! -d dotfiles-master ]; then
            echo 'dotfiles-master: not found'
            exit 1
        fi
        command mv -f dotfiles-master "$DOTPATH"

    else
        echo 'Required git or curl'
        exit 1
    fi

    e_done "Download dotfiles"
}

run_ansible() {
    echo 'run Ansible...'
    "$DOTPATH/ansible/run.sh"
    e_done "run Ansible"
}

main() {
    print_dotfiles_header
    set_apt_mirror
    install_ansible
    download_dotfiles
    run_ansible
}

main
