#!/bin/bash

DOTPATH=~/dotfiles; export DOTPATH
GITHUB_URL="https://github.com/shinshu68/dotfiles.git"; export GITHUB_URL

is_exists() {
    which "$1" >/dev/null 2>&1
    return $?
}

e_done() {
    printf " \033[37;1m%s\033[m...\033[32mOK\033[m\n" "✔ $*"
}

print_dotfiles_header() {
    printf "\e[34m"
    echo '---------------------------------------------------------------------------------------'
    echo '                                                                                       '
    echo '                 888            888      .d888  d8b  888                               '
    echo '                 888            888     d88P"   Y8P  888                               '
    echo '                 888            888     888          888                               '
    echo '             .d88888   .d88b.   888888  888888  888  888   .d88b.   .d8888b            '
    echo '            d88" 888  d88""88b  888     888     888  888  d8P  Y8b  88K                '
    echo '            888  888  888  888  888     888     888  888  88888888  "Y8888b.           '
    echo '            Y88b 888  Y88..88P  Y88b.   888     888  888  Y8b.           X88           '
    echo '             "Y88888   "Y88P"    "Y888  888     888  888   "Y8888    88888P"           '
    echo '                                                                                       '
    echo '---------------------------------------------------------------------------------------'
    printf "\e[0m\n"
}

download_dotfiles() {
    echo 'Downloading dotfiles...'

    if is_exists "git"; then
        git clone "$GITHUB_URL" "$DOTPATH"

    elif is_exists "curl"; then
        local tar_url="https://github.com/shinshu68/dotfiles/archive/master.tar.gz"
        curl -L "$tar_url" | tar xvz

        if [ ! -d dotfiles-master ]; then
            echo 'dotfiles-master: not found'
            exit 1
        fi
        command mv -f dotfiles-master "$DOTPATH"

    else
        echo 'Required git or curl'
        exit 1
    fi

    e_done "Download dotfiles"
}

install_ansible() {
    if is_exists "ansible"; then
        echo 'Already installed ansible'
        return
    fi

    echo 'Installing ansible...'
    yes | apt-add-repository ppa:ansible/ansible
    yes | apt update
    yes | apt install ansible

    e_done "Installi ansible"
}

print_dotfiles_header
download_dotfiles
install_ansible
