- set_fact:
    anyenv: {}

- name: fetch anyenv repo
  git:
    repo:    https://github.com/riywo/anyenv
    dest:    '{{ anyenv.dir }}'
  when: anyenv.dir

- name: create plugins dir
  file:
    dest:  '{{ anyenv.plugins_dir }}'
    state: directory
  when: anyenv.plugins_dir

- name: fetch anyenv update repo
  git:
    repo: https://github.com/znz/anyenv-update
    dest: '{{ anyenv.plugins_dir }}/anyenv-update'
  when: anyenv.plugins_dir

- name: export anyenv path
  blockinfile:
    path: '{{ home_path }}/.bash_profile'
    create: yes
    block: |
      export PATH="$HOME/.anyenv/bin:$PATH"
      eval "$(anyenv init -)"

- name: bash restart
  command: |
    bash -lc 'exec $SHELL -l'

- name: anyenv init
  command: |
    bash -lc 'yes | anyenv install --init'
