- set_fact:
    discord: {}

- stat:
    path: '{{ home_path }}/Downloads'
  register: downloads

- file:
    path:  '{{ home_path }}/Downloads'
    state: directory
    mode:  0755
  when: not downloads.stat.exists

- name: get discord deb file
  get_url:
    url:  "https://discordapp.com/api/download?platform=linux&format=deb"
    dest: "{{ home_path }}/Downloads/discord-app.deb"

- name: install discord
  become: yes
  apt:
    deb: "{{ home_path }}/Downloads/discord-app.deb"

- name: remove discord deb file
  file:
    path:  "{{ home_path }}/Downloads/discord-app.deb"
    state: absent
