- set_fact:
    vivaldi: {}

- name: check vivaldi
  stat:
    path: '/usr/bin/vivaldi'
  register: vivaldi

- block:
  - name: get vivaldi deb file
    get_url:
      url:  'https://downloads.vivaldi.com/stable/vivaldi-stable_2.9.1705.41-1_amd64.deb'
      dest: '{{ home_path }}/Downloads/vivaldi-stable_2.9.1705.41-1_amd64.deb'

  - name: install vivaldi
    become: yes
    apt:
      deb: '{{ home_path }}/Downloads/vivaldi-stable_2.9.1705.41-1_amd64.deb'

  - name: remove vivaldi deb file
    file:
      path:  '{{ home_path }}/Downloads/vivaldi-stable_2.9.1705.41-1_amd64.deb'
      state: absent

  when: not vivaldi.stat.exists
