[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'shinshu68/vim-code-dark'

[[plugins]]
repo = 'jdkanani/vim-material-theme'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
'''
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_config = {
    \  "_" : { "outputter/buffer/into" : 1,},}
'''

[[plugins]]
repo = 'skywind3000/asyncrun.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'benekastah/neomake'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
