syntax off

au FileType markdown setlocal foldmethod=marker
au BufRead,BufNewFile *.fish set filetype=fish

set modeline

" エディタウィンドウの末尾から2行目にステータスラインを常時表示させる
set laststatus=2
" ステータス行に表示させる情報の指定(どこからかコピペしたので細かい意味はわかっていない)
set statusline=%<%f\%m%r%h%w%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}%=%l,%c%V%8P

set expandtab

set tabstop=4

set softtabstop=4

set shiftwidth=4

set shiftround

set autoindent

set number

set ruler

set visualbell t_vb=
set noerrorbells

set matchpairs& matchpairs+=<:>

set showmatch

set matchtime=3

set wrap

set noswapfile

set showbreak=↪

set infercase

set ignorecase

set smartcase

set incsearch

set hlsearch

nnoremap <silent><Esc><Esc> :<C-u>set nohlsearch!<CR>

set wildmenu

set history=10000

set showmode

set showcmd

set scrolloff=5

set list
set listchars=tab:⊳-,trail:‗

inoremap <silent> jj <ESC>
inoremap <silent> ｊｊ <ESC>

let mapleader = "\<Space>"
nnoremap <Leader>w :w<CR>
nnoremap <Leader>h ^
nnoremap <Leader>l $
nnoremap <Leader>/ *
nnoremap <Leader>m %

function! s:isWsl()
    return filereadable('/proc/sys/fs/binfmt_misc/WSLInterop')
endfunction

if s:isWsl() && executable('AutoHotkeyU64.exe')
    augroup insertLeave
        autocmd!
        autocmd InsertLeave * :call system('AutoHotkeyU64.exe "D:\ImDisable.ahk"')
    augroup END
endif

function! s:InputPrefix(prefix)
    execute "normal ggi" . a:prefix . ' '
endfunction
command! -nargs=1 InputPrefix call s:InputPrefix(<f-args>)

function! s:InsertClose(number)
    execute "normal 2o\<ESC>iclose " . a:number
endfunction
command! -nargs=1 InsertClose call s:InsertClose(<f-args>)

