version: '3'
services:
    development:
        build: .
        command: fish
        environment:
            - DOCKER_MACHINE_NAME=dev
            - GID=${GROUP_ID}
            - INSIDE_DOCKER=1
            - SSH_AUTH_SOCK=/ssh-agent
            - TERM=xterm-256color
            - TZ=Asia/Tokyo
            - UID=${USER_ID}
            - USERNAME=shinshu
        image: shinshu68/development-env
        tty: true
        volumes:
            - /home/${USER}:/home/${USER}
            - /home/${USER}:/home/shinshu
            - /var/run/docker.sock:/var/run/docker.sock
            - ${SSH_AUTH_SOCK}:/ssh-agent
        working_dir: /home/shinshu
