version: '3'
services:
    development:
        build: .
        command: fish
        environment:
            - XDG_RUNTIME_DIR=/run/user/${USER_ID}
            - UID=${USER_ID}
            - GID=${GROUP_ID}
        image: shinshu68/development-env
        tty: true
        volumes:
            - /home/${USER}:/home/${USER}
            - /home/${USER}:/home/shinshu
            - /var/run/docker.sock:/var/run/docker.sock
        working_dir: /home/shinshu
