- set_fact:
    desktop: {}

- name: apt install
  become: yes
  apt:
    name:             '{{ desktop.apt.packages }}'
    update_cache:     yes
    cache_valid_time: 3600

- name: set terminal desktop entry
  become: yes
  replace:
    dest:    /usr/share/applications/gnome-terminal.desktop
    regexp:  '^OnlyShowIn=GNOME;Unity;'
    replace: '# OnlyShowIn=GNOME;Unity;'

- name: purge the package 'pantheon-terminal'
  apt:
    name:  pantheon-terminal
    state: absent

- block:
  - name: package install (from AppCenter)
    become: yes
    apt:
      name:             '{{ desktop.appcenter.packages }}'
      update_cache:     yes
      cache_valid_time: 3600
  when: ansible_distribution == "elementary OS"

- name: check Cica font
  stat:
    path: '{{ home_path }}/.local/share/fonts/Cica-Regular.ttf'
  register: Cica

- name: create font directory
  file:
    path:  '{{ home_path }}/.local/share/fonts'
    state: directory
    mode:  0755

- block:
  - name: download Cica
    get_url:
      url:  'https://github.com/miiton/Cica/releases/download/v5.0.1/Cica_v5.0.1_with_emoji.zip'
      dest: '{{ home_path }}/Downloads/Cica_v5.0.1_with_emoji.zip'

  - name: unzip Cica
    unarchive:
      src: '{{ home_path }}/Downloads/Cica_v5.0.1_with_emoji.zip'
      dest: '{{ home_path }}/.local/share/fonts'

  - name: cache font
    shell: fc-cache -fv

  - dconf:
      key: '{{ item.key }}'
      value: '{{ item.value | quote }}'
      state: present
    loop_control:
      label: '{{ item.key }}'
    with_dict:
      - /org/gnome/desktop/interface/monospace-font-name: Cica 12
      - /org/gnome/desktop/interface/document-font-name: Cica 12
      - /org/gnome/desktop/interface/font-name: Cica 12

  when: not Cica.stat.exists

