- set_fact:
    desktop: {}

- name: apt install
  become: yes
  apt:
    name:             '{{ desktop.apt.packages }}'
    update_cache:     yes
    cache_valid_time: 3600

- name: set GNOME terminal desktop entry
  become: yes
  replace:
    dest:    /usr/share/applications/gnome-terminal.desktop
    regexp:  '^OnlyShowIn=GNOME;Unity;'
    replace: '# OnlyShowIn=GNOME;Unity;'

- name: get gnome terminal profile id
  shell: 'gsettings get org.gnome.Terminal.ProfilesList default'
  register: profile
  changed_when: false

- name: set gnome terminal profile
  dconf:
    key: >-
      /org/gnome/terminal/legacy/profiles:/:{{ profile.stdout | replace("'", "") }}/{{ item.key }}
    state: present
    value: '{{ item.value }}'
  loop_control:
    label: '{{ item.key }}'
  with_dict: '{{ desktop.gnome.terminal }}'
- block:
  - name: package install (from AppCenter)
    become: yes
    apt:
      name:             '{{ desktop.appcenter.packages }}'
      update_cache:     yes
      cache_valid_time: 3600
  when: ansible_distribution == "elementary OS"

- name: purge 'pantheon-terminal'
  become: yes
  apt:
    name:  pantheon-terminal
    state: absent

- name: check Cica font
  stat:
    path: '{{ home_path }}/.local/share/fonts/Cica-Regular.ttf'
  register: Cica

- name: create font directory
  file:
    path:  '{{ home_path }}/.local/share/fonts'
    state: directory
    mode:  0755

- block:
  - name: download Cica
    get_url:
      url:  'https://github.com/miiton/Cica/releases/download/v5.0.1/Cica_v5.0.1_with_emoji.zip'
      dest: '{{ home_path }}/Downloads/Cica_v5.0.1_with_emoji.zip'

  - name: unzip Cica
    unarchive:
      src: '{{ home_path }}/Downloads/Cica_v5.0.1_with_emoji.zip'
      dest: '{{ home_path }}/.local/share/fonts'

  - name: cache font
    shell: fc-cache -fv

  - name: setting font
    dconf:
      key: '{{ item.key }}'
      value: '{{ item.value | quote }}'
      state: present
    loop_control:
      label: '{{ item.key }}'
    with_dict:
      - /org/gnome/desktop/interface/monospace-font-name: Cica 12
      - /org/gnome/desktop/interface/document-font-name: Cica 12
      - /org/gnome/desktop/interface/font-name: Cica 12

  when: not Cica.stat.exists

- name: check plank
  stat:
    path: /usr/bin/plank
  register: plank

- block:
  - name: create plank config directory
    file:
      path:  '{{ home_path }}/.config/plank/dock1/launchers'
      state: directory
      mode:  0755

  - name: check application desktop file
    stat:
      path: '/usr/share/applications/{{ item }}.desktop'
    with_items: '{{ desktop.plank.dock_items }}'
    register: application_file

  - name: configure dock items
    template:
      src:   'launcher.dockitem.j2'
      dest:  '{{ home_path }}/.config/plank/dock1/launchers/{{ item.item }}.dockitem'
      owner: '{{ user_name }}'
      group: '{{ user_name }}'
      mode:  0644
    loop_control:
      label: '{{ item.item }}'
    when: item.stat.exists
    with_items: '{{ application_file.results }}'

  when: plank.stat.exists

- name: vscode task
  include_tasks: vscode.yml
