- set_fact:
    vscode_path: '{{ home_path }}/.config/Code/User'

- name: check vscode
  stat:
    path: '/usr/bin/code'
  register: vscode_stat

- block:
  - name: install key
    become: yes
    apt_key:
      url:  https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: add vscode repository
    become: yes
    apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
      filename: vscode
      state: present

  - name: apt update
    become: yes
    apt:
      update_cache: yes

  - name: install vscode
    become: yes
    apt:
      name:  'code'
      state: present

  when: not vscode_stat.stat.exists

- name: create parent directories
  file:
    dest:    '{{ vscode_path }}/{{ item }}'
    state:   directory
    recurse: yes
  loop_control:
    label: '{{ vscode_path }}/{{ item }}'
  with_items: '{{ desktop.vscode.link.values() | map("dirname") | unique | list }}'

- name: check destinations
  stat:
    path: '{{ vscode_path }}/{{ item.value }}'
  loop_control:
    label: '{{ item.value }}'
  with_dict: '{{ desktop.vscode.link }}'
  register: dest_stat

- name: create backup files
  command: |
    mv -f \
      {{ vscode_path | quote }}/{{ item.item.value | quote }} \
      {{ vscode_path | quote }}/{{ item.item.value | quote }}.bak
  when: item.stat.exists and not item.stat.islnk
  loop_control:
    label: '{{ item.item.value }}'
  with_items: '{{ dest_stat.results }}'

- name: create symlinks
  file:
    src:   '{{ dotfiles_path }}/{{ item.key }}'
    dest:  '{{ vscode_path }}/{{ item.value }}'
    state: link
    force: yes
  loop_control:
    label: '{{ item.value }}'
  with_dict: '{{ desktop.vscode.link }}'

- name: get installed vscode extensions
  command: |
    code --list-extensions
  register: installed_extensions
  changed_when: False

- name: install extensions
  command: | 
    code --install-extension {{ item | quote }}
  when: desktop.vscode.extensions and installed_extensions.stdout.find(item) == -1
  with_items: '{{ desktop.vscode.extensions }}'
