- set_fact:
    pip: {}
    ansible_python_interpreter: '{{ anyenv.envs_dir }}/pyenv/shims/python'

- name: pip3 install
  pip:
    name: '{{ pip.packages }}'
  when: pip.packages

- name: pip3 install --upgrade
  pip:
    name:       '{{ pip.packages }}'
    extra_args: --upgrade
  when: pip.packages

- set_fact:
    pip: {}
    ansible_python_interpreter: '{{ anyenv.envs_dir }}/pyenv/shims/python2'

- name: pip2 install
  pip:
    name: '{{ pip.packages }}'
  when: pip.packages

- name: pip2 install --upgrade
  pip:
    name:       '{{ pip.packages }}'
    extra_args: --upgrade
  when: pip.packages

- set_fact:
    pip: {}
    ansible_python_interpreter: '/usr/bin/python'

  pip:
    name: pysutil
