- set_fact:
    pip: {}

- name: pip install
  pip:
    name:       '{{ pip.packages }}'
    state:      latest
    executable: '{{ anyenv.envs_dir }}/pyenv/versions/{{ python.versions[0] }}/bin/pip'
  when: pip.packages
