- name: add fish repo
  apt_repository:
    repo:         'ppa:fish-shell/release-2'
    state:        present
    update_cache: yes

- name: install fish
  apt:
    name:         'fish'
    state:        present
    update_cache: yes

