- name: add fish repo
  become: yes
  apt_repository:
    repo:         'ppa:fish-shell/release-2'
    state:        present
    update_cache: yes

- name: install fish
  become: yes
  apt:
    name:         'fish'
    state:        present
    update_cache: yes

- name: create dir
  file:
    path:  '{{ home_path }}/.config/fish/functions'
    state: directory
    mode:  0755

- name: install fisher
  get_url:
    url:  https://git.io/fisher
    dest: '{{ home_path }}/.config/fish/functions/fisher.fish'

- name: install fish theme
  command: |
    fish -c "fisher add oh-my-fish/theme-bobthefish"

