- set_fact:
    dotfiles_fish_config_path: '{{ dotfiles_path }}/config/fish/'

- name: add fish repository
  become: yes
  apt_repository:
    repo:         'ppa:fish-shell/release-3'
    state:        present
    update_cache: yes

- name: install fish
  become: yes
  apt:
    name:             'fish'
    state:            present
    update_cache:     yes
    cache_valid_time: 3600

- name: check fish config functions directory
  stat:
    path:   '{{ home_path }}/.config/fish/functions'
  register: config_stat

- name: create fish config directory
  file:
    path:  '{{ home_path }}/.config/fish/functions'
    state: directory
    mode:  0755
  when: not config_stat.stat.exists

- name: check installed fisher
  stat:
    path:   '{{ home_path }}/.config/fish/functions/fisher.fish'
  register: fisher_stat

- name: install fisher
  get_url:
    url:  https://git.io/fisher
    dest: '{{ home_path }}/.config/fish/functions/fisher.fish'
  when: not fisher_stat.stat.exists

- name: update fisher
  command: |
      fish -c "fisher self-update"
  when: fisher_stat.stat.exists
  changed_when: False

- name: check installed fisher plugins
  command: |
      fish -c "fisher ls"
  register: installed_fisher_plugins
  changed_when: False

- name: install fisher plugins
  command: |
    fish -c "fisher add {{ item | quote }}"
  when: |
    installed_fisher_plugins.stdout.find(item) == -1
  with_items: '{{ fish.fisher_plugins }}'

- name: get fish config files
  find:
    paths:   '{{ dotfiles_fish_config_path }}'
    recurse: yes
  register: fish_files

- name: create symlinks
  file:
    src:   '{{ item.path }}'
    dest:  '{{ home_path }}/.config/fish/{{ item.path[dotfiles_fish_config_path|length:] }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    state: link
    force: yes
  loop_control:
    label: '{{ item.path | basename }}'
  with_items: '{{ fish_files.files }}'
