- set_fact:
    python: {}

- name: check pyenv
  command: |
    bash -lc 'which pyenv'
  register: which_pyenv
  ignore_errors: yes

- name: install pyenv
  command: |
    bash -lc 'anyenv install pyenv'
  when: which_pyenv.rc > 0

- name: get installed versions
  command: |
    bash -lc 'pyenv versions'
  register: installed_versions

- name: install python3
  command: |
    bash -lc 'pyenv install {{ item | quote }}'
  when: |
    python.version3 and installed_versions.stdout.find(item) == -1
  with_items: '{{ python.version3 }}'

- name: install python2
  command: |
    bash -lc 'pyenv install {{ item | quote }}'
  when: |
    python.version2 and installed_versions.stdout.find(item) == -1
  with_items: '{{ python.version2 }}'

- name: set global python
  command: |
    bash -lc 'pyenv global {{ python.version3[0] | quote }} {{ python.version2[0] | quote}}'

- name: rehash
  shell: |
    if [ -f "$DOTSHIM_FILE" ]; then
      rm -f "$DOTSHIM_FILE"
    fi
    bash -lc 'pyenv rehash'
  environment:
    DOTSHIM_FILE: '{{ anyenv.envs_dir }}/pyenv/.pyenv-shim'
