anyenv:
  dir:         '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path }}/.anyenv/pluins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'

apt:
  repositories:
    - ppa:dawidd0811/neofetch
    - ppa:neovim-ppa/stable

  packages:
    - direnv
    - git
    - golang-1.10
    - haskell-platform
    - neofetch
    - neovim
    - nodejs
    - npm
    - p7zip-full
    - python-pip
    - python3-pip
    - tmux
    - tree
    - vim-nox
    - xclip
    - xsel

python:
  pyenv:
    suggest_packages:
      - build-essential
      - curl
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxmlsec1-dev
      - llvm
      - make
      - tk-dev
      - wget
      - xz-utils
      - zlib1g-dev

  version2:
    - '2.7.15'
  version3:
    - '3.7.2'

pip:
  packages:
    - PyGithub
    - beautifulsoup4
    - flake8
    - flask
    - gitPython
    - inquirer
    - jedi
    - matplotlib
    - neovim
    - numpy
    - pipreqs
    - pyperclip
    - pyyaml
    - readchar
    - requests
    - truecolor
    - youtube_dl

fish:
  fisher_plugins:
    - jethrokuan/fzf
    - oh-my-fish/theme-bobthefish

link:
  bash/bashrc:    .bashrc
  config/flake8:  .config/flake8
  config/nvim:    .config/nvim
  git/gitconfig:  .gitconfig
  tmux/tmux.conf: .tmux.conf
  vim/vimrc:      .vimrc

vscode:
  link:
    config/Code/settings.json: settings.json

  extensions:
    - CoenraadS.bracket-pair-colorizer
    - Dart-Code.dart-code
    - Dart-Code.flutter
    - DavidAnson.vscode-markdownlint
    - MS-CEINTL.vscode-language-pack-ja
    - PKief.material-icon-theme
    - christian-kohler.path-intellisense
    - dbaeumer.vscode-eslint
    - donjayamanne.githistory
    - eamodio.gitlens
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    - justusadam.language-haskell
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-vscode.cpptools
    - ms-vscode.csharp
    - ms-vscode.vs-keybindings
    - oderwat.indent-rainbow
    - twxs.cmake
    - vector-of-bool.cmake-tools
    - vsciot-vscode.vscode-arduino
    - vscodevim.vim
    - xyz.plsql-language
