anyenv:
  dir:         '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path }}/.anyenv/pluins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'

apt:
  repositories:
    - ppa:dawidd0811/neofetch
    - ppa:neovim-ppa/stable

  packages:
    - cmake
    - dconf-tools
    - direnv
    - git
    - gdebi
    - golang-1.10
    - libclang-dev
    - neofetch
    - neovim
    - nodejs
    - npm
    - p7zip-full
    - python-apt
    - python-pip
    - python3-pip
    - tmux
    - tree
    - vim-nox
    - xclip
    - xsel

desktop:
  apt:
    packages:
      - fcitx
      - fcitx-mozc
      - gnome-system-monitor
      - gnome-terminal
      - gparted

  appcenter:
    packages:
      - com.github.davidmhewitt.clipped

  gnome:
    terminal:
      audible-bell: 'false'
      background-color: "'rgb(0,0,0)'"
      background-transparency-percent: 13
      foreground-color: "'rgb(255,255,255)'"
      use-theme-colors: 'false'
      use-theme-transparency: 'false'
      use-transparent-background: 'true'

  plank:
    dock_items:
      - google-chrome
      - vivaldi-stable
      - slack
      - io.elementary.files
      - gnome-system-monitor
      - io.elementary.appcenter
      - io.elementary.switchboard
      - code
      - org.gnome.Terminal

  vscode:
    link:
      config/Code/settings.json: settings.json

    extensions:
      - CoenraadS.bracket-pair-colorizer
      - Dart-Code.dart-code
      - Dart-Code.flutter
      - DavidAnson.vscode-markdownlint
      - MS-CEINTL.vscode-language-pack-ja
      - PKief.material-icon-theme
      - XadillaX.viml
      - alanz.vscode-hie-server
      - bungcip.better-toml
      - christian-kohler.path-intellisense
      - dbaeumer.vscode-eslint
      - donjayamanne.githistory
      - eamodio.gitlens
      - formulahendry.auto-close-tag
      - formulahendry.auto-rename-tag
      - justusadam.language-haskell
      - ms-azuretools.vscode-docker
      - ms-python.python
      - ms-vscode.cmake-tools
      - ms-vscode.cpptools
      - ms-vscode.csharp
      - ms-vscode.vs-keybindings
      - oderwat.indent-rainbow
      - skyapps.fish-vscode
      - twxs.cmake
      - vsciot-vscode.vscode-arduino
      - vscodevim.vim
      - vscoss.vscode-ansible
      - xyz.plsql-language

python:
  version2:
    - '2.7.15'
  version3:
    - '3.7.2'

pip:
  packages:
    - PyGithub
    - beautifulsoup4
    - click
    - flake8
    - flask
    - gitPython
    - inquirer
    - jedi
    - matplotlib
    - neovim
    - numpy
    - pipreqs
    - pyperclip
    - pyyaml
    - readchar
    - requests
    - toml
    - truecolor
    - youtube_dl

fish:
  fisher_plugins:
    - jethrokuan/fzf
    - oh-my-fish/theme-bobthefish

link:
  bash/bashrc:    .bashrc
  config/flake8:  .config/flake8
  config/prepost: .config/prepost
  config/nvim:    .config/nvim
  git/gitconfig:  .gitconfig
  tmux/tmux.conf: .tmux.conf
  vim/vimrc:      .vimrc

others:
  repos:
    - repo: 'git@github.com:shinshu68/PrePost.git'
      dest: '{{ home_path }}/workspace/prepost'
    - repo: 'git@github.com:shinshu68/emoji-fish.git'
      dest: '{{ home_path }}/workspace/emoji-fish'
    - repo: 'git@github.com:shinshu68/BookShelf.git'
      dest: '{{ home_path }}/workspace/bookshelf'
    - repo: 'git@github.com:toyota-ct-selab/shinshu_works.git'
      dest: '{{ home_path }}/shinshu_works'
