anyenv:
  dir:         '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path }}/.anyenv/pluins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'

apt:
  repositories:
    - ppa:neovim-ppa/stable

  packages:
    - direnv
    - git
    - golang-1.10
    - neovim
    - python-pip
    - python3-pip
    - tmux
    - vim-nox

user:
  default_shell:
    - shell: '/usr/bin/fish'

python:
  pyenv:
    suggest_packages:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
  version2:
    - '2.7.15'
  version3:
    - '3.7.2'

pip:
  packages:
    - flake8
    - jedi
    - neovim

link:
  bash/bashrc:                         .bashrc
  config/fish/config.fish:             .config/fish/config.fish
  config/fish/functions/cls.fish:      .config/fish/functions/cls.fish
  config/fish/functions/hisgre.fish:   .config/fish/functions/hisgre.fish
  config/fish/functions/reporoot.fish: .config/fish/functions/reporoot.fish
  config/gitconfig:                    .gitconfig
  config/nvim:                         .config/nvim
  tmux/tmux.conf:                      .tmux.conf
  vim/vimrc:                           .vimrc
