services:
    # 作業中のリポジトリをマウントして playbook を試す
    ansible:
        build: ./Dockerfiles/ansible
        volumes:
            - ..:/home/shinshu/dotfiles
        tty: true

    # 何も入っていない状態から install スクリプトを試す
    vanilla:
        build: ./Dockerfiles/vanilla
        tty: true
