- name:  shinshu68 development environment
  hosts: 127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'
    user_name:     '{{ lookup("env", "USER") }}'

  roles:
    - role: apt
      tags: ['apt']
    - role: fish
      tags: ['fish']
    - role: anyenv
      tags: ['anyenv']
    - role: python
      tags: ['python']
    - role: pip
      tags: ['pip']
    - role: vscode
      tags: ['vscode']
    - role: link
      tags: ['link']
    - role: others
      tags: ['others']
    - role: test
      tags: ['test']
