- name:  shinshu68 test
  hosts: test_servers
  connection: docker

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'
    user_name:     '{{ lookup("env", "USER") }}'

  roles:
    - role: apt
      tags: ['install', 'apt']
    - role: fish
      tags: ['install', 'fish']
    - role: pip
      tags: ['install', 'pip']
    - role: link
      tags: ['link']
