- name:  shinshu68 development environment
  hosts: 127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'
    user_name:     '{{ lookup("env", "USER") }}'

  roles:
    - role: apt
      tags: ['install', 'apt']
    - role: fish
      tags: ['install', 'fish']
    - role: anyenv
      tags: ['base', 'anyenv']
    - role: python
      tags: ['lang', 'python']
    - role: pip
      tags: ['install', 'pip']
    - role: link
      tags: ['base', 'link']
    - role: vscode
      tags: ['editor', 'vscode']
