- set_fact:
    apt: {}

- name: apt add repositories
  apt_repository:
    repo:         '{{ item }}'
    update_cache: no
  with_items: '{{ apt.repositories }}'
  when: apt.repositories

- name: apt update
  apt:
    update_cache: yes

- name: apt install
  apt:
    name:             '{{ item }}'
    update_cache:     yes
    cache_valid_time: 3600
    state:            latest
  with_items: '{{ apt.packages }}'
  when: apt.packages

