[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_event = 'InsertEnter'
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    call deoplete#custom#option({
    \ 'auto_complete_delay': 1,
    \ 'num_processes': 4,
    \ 'refresh_always': v:true,
    \ })
    inoremap <expr><tab> pumvisible() ? "\<C-n>" : "\<tab>"
'''

#hook_source = '''
#    let g:deoplete#enable_at_startup = 1
#    let g:deoplete#auto_complete_delay = 0
#    let g:deoplete#auto_complete_start_length = 1
#    let g:deoplete#enable_camel_case = 0
#    let g:deoplete#enable_ignore_case = 0
#    let g:deoplete#enable_refresh_always = 0
#    let g:deoplete#enable_smart_case = 1
#    let g:deoplete#file#enable_buffer_path = 1
#    let g:deoplete#max_list = 10000
#    inoremap <expr><tab> pumvisible() ? "\<C-n>" : "\<tab>"
#'''

[[plugins]]
repo = 'zchee/deoplete-clang'
hook_source = '''
    let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-6.0/lib/libclang.so.1'
    let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']
#\ neosnippet#expandable_or_jumpable() ?
#\    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"


[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'sophacles/vim-processing'
on_ft = ['processing']

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTree'
hook_add = '''
    nnoremap <C-n> :NERDTree<CR>
    let g:NERDTreeShowHidden=1
    let g:NERDTreeShowBookmarks=1
'''

[[plugins]]
repo = 'reireias/vim-cheatsheet'
on_cmd = 'Cheat'
hook_add = '''
    autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
    let g:cheatsheet#cheat_file = "~/dotfiles/.cheatsheet.md"
'''

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

[[plugins]]
repo = 'himanoa/ttene.nvim'
on_i = 1
hook_post_update = '''
    let g:dein#plugin.build = 'magicalstick | grep "てねっ[0-9]" | xargs -P4 -In1 wget n1 -P voices/'
'''

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = 'markdown'

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = 'markdown'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = 'markdown'
hook_add = '''
    let g:vim_markdown_folding_disabled = 1
'''
