[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasiser/vim-code-dark'


[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'thinca/vim-quickrun'


[[plugins]]
repo = 'skywind3000/asyncrun.vim'
