[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_event = 'InsertCharPre'
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    call deoplete#custom#option({
    \ 'auto_complete_delay': 1,
    \ 'num_processes': 4,
    \ 'refresh_always': v:true,
    \ })
    inoremap <expr><tab> pumvisible() ? "\<C-n>" : "\<tab>"
    inoremap <expr><S-tab> pumvisible() ? "\<C-p>" : "\<S-tab>"
'''
#hook_source = '''
#    let g:deoplete#enable_at_startup = 1
#    let g:deoplete#auto_complete_delay = 0
#    let g:deoplete#auto_complete_start_length = 1
#    let g:deoplete#enable_camel_case = 0
#    let g:deoplete#enable_ignore_case = 0
#    let g:deoplete#enable_refresh_always = 0
#    let g:deoplete#enable_smart_case = 1
#    let g:deoplete#file#enable_buffer_path = 1
#    let g:deoplete#max_list = 10000
#    inoremap <expr><tab> pumvisible() ? "\<C-n>" : "\<tab>"
#'''

[[plugins]]
repo = 'zchee/deoplete-clang'
hook_source = '''
    let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-6.0/lib/libclang.so.1'
    let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']
#\ neosnippet#expandable_or_jumpable() ?
#\    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'sophacles/vim-processing'
on_ft = ['processing']

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTree'
hook_add = '''
    nnoremap <C-n> :NERDTree<CR>
    let g:NERDTreeShowHidden=1
    let g:NERDTreeShowBookmarks=1
'''

[[plugins]]
repo = 'reireias/vim-cheatsheet'
on_cmd = 'Cheat'
hook_add = '''
    autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
    let g:cheatsheet#cheat_file = "~/dotfiles/.cheatsheet.md"
'''

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

[[plugins]]
repo = 'himanoa/ttene.nvim'
on_i = 1
hook_post_update = '''
    let g:dein#plugin.build = 'magicalstick | grep "てねっ[0-9]" | xargs -P4 -In1 wget n1 -P voices/'
'''

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = 'markdown'

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = 'markdown'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = 'markdown'
hook_add = '''
    let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'w0rp/ale'
on_ft = 'python'
hook_add = '''
    highlight clear ALEErrorSign
    highlight clear ALEWarningSign
    let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
    let g:ale_sign_column_always = 1

    let g:ale_lint_on_insert_leave = 1
    let g:ale_lint_on_save = 1
    let g:ale_lint_on_text_changed = 1

    let g:ale_set_loclist = 0
    let g:ale_set_quickfix = 0
    let g:ale_open_list = 0
    let g:ale_keep_list_window_open = 0

    let g:ale_linters = {
    \   'python': ['flake8'],
    \}

    nmap [ale] <Nop>
    map <C-k> [ale]
    nmap <silent> [ale]<C-P> <Plug>(ale_previous)
    nmap <silent> [ale]<C-N> <Plug>(ale_next)
'''

[[plugins]]
repo = 'yuroyoro/vim-scala'
on_ft = 'scala'
hook_source = '''
    setlocal dictionary+=~/.cache/dein/repos/github.com/yuroyoro/vim-scala/dict/scala.dict
'''

#[[plugins]]
#repo = 'neomake/neomake'
#on_ft = ['python']
#hook_source = '''
#    autocmd! BufEnter,BufWritePost * Neomake
#    let g:neomake_python_enabled_makers = ['python', 'flake8']
#'''
